### ISSUE TITLE
Fix attaching the TimeTablePagerFragment from the backstack

### ISSUE THREAD

**Issue by shalzz** [shalzz/college-academics#2]
In https://github.com/Shalzz/upes-academics/blob/dev/attendance/src/main/java/com/shalzz/attendance/ui/main/MainActivity.java#L495
when restoring the TimeTablePagerFragment it doesn't redraw properly untill you swipe across it a couple of times. To workaround this we just create a new instance and display it which is not really desired.
See if you can fix it.

**Comment by SekthDroid** [comment]
Hi @Shalzz , I have been trying to debug this and I have something working that solves the problem, but Im just checking if there is some hidden behaviors ;).

I have one question to ask, when you are using the TimeTablePagerFragment, and the user is scrolling between the different days, but he goes to another app, and then he back to the app again, the TimeTablePagerFragment shows again with the current day, instead of the one that the user was watching, is this the expected behavior?

Example:
- Today is Monday
- User is watching the TimeTable for next Wednesday
- User leaves the app to check the email
- Android kills the activity
- User comes back to the app
- The TimeTable that is shown es Monday (should be Wednesday?)

Thanks ;)

**Comment by shalzz** [comment]
Hey @SekthDroid, thanks for looking into this.
Yes thats expected as the TimeTablePagerFragment calls the controllers setToday() method in onStart()  (maybe I should move it to onCreateView) which scrolls the pager to the current day.
